//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lab01
{
    using System;
    using System.Collections.Generic;
    
    public partial class BusinessSpecifics
    {
        public int id { get; set; }
        public string name { get; set; }
        public string price { get; set; }
        public Nullable<double> rating { get; set; }
        public Nullable<int> review_count { get; set; }
        public Nullable<double> distance { get; set; }
        public string alias { get; set; }
        public string image_url { get; set; }
        public string phone { get; set; }
        public string url { get; set; }
        public Nullable<System.DateTime> data { get; set; }
        public string city { get; set; }
        public string category { get; set; }
        public string region { get; set; }
        public string country { get; set; }
    }
}
